webtalk_init -webtalk_dir F:/TA/2021 Spring/HWSEC/Vivado Project/Accumulator/Accumulator.sim/sim_1/impl/timing/xsim/xsim.dir/test_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 21 23:09:51 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211585811_1777537819_210689844_420" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0e9c91b3-d4ad-4b25-ae7f-c2d85277524b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "450c3b1a212d448cbbc7da57ea548897" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1190 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7380_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2729971234 -regid "211585811_1777537819_210689844_420" -xml F:/TA/2021 Spring/HWSEC/Vivado Project/Accumulator/Accumulator.sim/sim_1/impl/timing/xsim/xsim.dir/test_time_impl/webtalk/usage_statistics_ext_xsim.xml -html F:/TA/2021 Spring/HWSEC/Vivado Project/Accumulator/Accumulator.sim/sim_1/impl/timing/xsim/xsim.dir/test_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm F:/TA/2021 Spring/HWSEC/Vivado Project/Accumulator/Accumulator.sim/sim_1/impl/timing/xsim/xsim.dir/test_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
